#!/bin/bash

# Usage: drupaldump user password database
# http://www.millwoodonline.co.uk/blog/how-to-effectively-dump-drupal-database

USER="$1"
PASS="$2"
DB="$3"
HOST="localhost"
DATE=`date +%Y-%m-%dT%H%M`
OUTPUT_FILE="db-${DB}--${DATE}.sql"

# Dump structure.
echo "==> Dumping table structure."
TABLES=`mysql --skip-column-names -e 'show tables' -u ${USER} -p${PASS} -h ${HOST} ${DB}`
mysqldump --complete-insert --disable-keys --single-transaction --no-data -u ${USER} --password=${PASS} -h ${HOST} ${DB} ${TABLES} > ${OUTPUT_FILE}

# Dump data, excluding certain tables.
echo "==> Dumping table data."
TABLES2=`echo "$TABLES" | grep -Ev "^(accesslog|cache.*|flood|search_.*|semaphore|sessions|watchdog)$"`
mysqldump --complete-insert --disable-keys --single-transaction --no-create-info -u ${USER} --password=${PASS} -h ${HOST} ${DB} ${TABLES2} >> ${OUTPUT_FILE}

echo "${OUTPUT_FILE} has been created."
