#!/bin/bash

# Usage: emptydb user password database

USER="$1"
PASS="$2"
DB="$3"
HOST="localhost"

TABLES=`mysql --skip-column-names -e 'show tables' -u ${USER} -p${PASS} -h ${HOST} ${DB}`
 
for table in $TABLES
do
  `mysql -e "drop table $table" -u ${USER} -p${PASS} -h ${HOST} ${DB}`
  echo "==> Database: ${DB} -- dropped table $table"
done
